spring:
  application:
    name: backend
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: desc
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

tour-api:
  base-url: https://apis.data.go.kr/B551011/KorService2
  service-key: ${TOUR_API_SERVICE_KEY:}
  mobile-os: ETC
  mobile-app: SIKCOURSE

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-millis: ${JWT_ACCESS_TOKEN_EXPIRATION_MILLIS:3600000}
